USE buffetabogados;

CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(255) NOT NULL UNIQUE,
nombre VARCHAR(180) NOT NULL,
apellido VARCHAR(180) NOT NULL,
telefono VARCHAR(90) NOT NULL UNIQUE,
imagen VARCHAR(255) NULL,
contraseña VARCHAR(255) NOT NULL,
created_at TIMESTAMP(0) NOT NULL,
update_at TIMESTAMP(0) NOT NULL
);